version: '3.0'
services:  
  flask:
    restart: always
    build: backend
    ports: 
      - "5000:5000"
    depends_on:
      - database
      - tomcat
  
  database:
    restart: always    
    image: postgres:10   
    environment:      
      - POSTGRES_USER="postgres"      
      - POSTGRES_PASSWORD="postgres"      
      - POSTGRES_DB="postgres"  
    ports:  
      - "5432:5432"

  tomcat: 
    restart: always
    build: tomcat
    ports: 
      - "8080:8080"
